name: MyWorkflows
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "**.spec.js"
      - ".idea"
      - ".vscode"
      - ".dockerignore"
      - "Dockerfile"
      - ".gitignore"
      - ".github/**"
      - "!.github/workflows/build.yml"

jobs:
  build-project:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install linux dependencies
        # if: runner.os == 'Linux'
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo "The operating system on the runner is $env:RUNNER_OS."
          sudo apt-get update -y && sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev build-essential pkg-config

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      
      - name: Setup Wails CLI v2.6.0
        run: go install github.com/wailsapp/wails/v2/cmd/wails@v2.6.0

      - name: Checkout Wails
        run: wails doctor

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  

      - name: Creating project with a template
        run: |
          cd ..
          wails init -n my-wails-project -t wails-vite-vue-ts-navie-pinia

      - name: Build Release Files
        run: |
          cd ../my-wails-project
          wails build
      
      - name: Tar files on Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd ../my-wails-project
          tar -cvf build_on_${{ matrix.os }}.tar ./build/bin/

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build_on_${{ matrix.os }}
          path: build/bin/
          retention-days: 5
        working-directory: ../my-wails-project/